apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: na64kmkzc-go 
  janus-idp.io/tekton: na64kmkzc-go
  backstage.io/kubernetes-id: na64kmkzc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: na64kmkzc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml