apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: na64kmkzc-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:59088dc7e240c8862c826d6b37cb8f7a8f50e404@sha256:a44defdace51d300ebc4215f48ca6d30ba63fe73773b519c791dcf31ec5d6698
          name: container-image
